### ISSUE TITLE
Incorrect 404 Not Found response when Accept header is invalid

### ISSUE THREAD

**Issue by kisdead** [killbill/killbill-paypal-express-plugin#3]
The plugin returns 404 with body `<h1>Not Found</h1>` when a valid Accept header was not sent with the request. Since curl automatically adds an `Accept: */*` header it doesn't happen with curl, however, it is easy to reproduce by forcing curl to send an empty Accept header with the `-H 'Accept:'` argument.

If you modify the example from the readme then you can reproduce the issue:

```
curl -v \
     -X POST \
     -u admin:password \
     -H 'Accept:' \
     -H 'X-Killbill-ApiKey: bob' \
     -H 'X-Killbill-ApiSecret: lazar' \
     -H 'X-Killbill-CreatedBy: admin' \
     -H 'Content-Type: text/plain' \
     -d ':paypal_express:
  :signature: "your-paypal-signature"
  :login: "your-username-facilitator.something.com"
  :password: "your-password"' \
     http://127.0.0.1:8080/1.0/kb/tenants/uploadPluginConfig/killbill-paypal-express
```

I suggest returning **406: Not Acceptable** instead.

Why does it need to be fixed: I'm using an advanced REST client that doesn't add Accept headers automatically, and I thought that something else was wrong because of the misleading response. Also, logs don't help either so I was left completely clueless. I wasted a day or so trying different versions of the plugin and Kill Bill to see if there is a version that works, and apparently no one has had the same issue before because I didn't find anything about this on the internet. If the response I got had been 406 it would have been trivial.

**Comment by sbrossie** [comment]
@kisdead if you want to provide a PR, we ll be happy to merge it.

**Comment by sbrossie** [comment]
By the way the fix would have to be it [killbill repo](https://github.com/killbill/killbill)

Since we are using jersey, that might be a good place to [start](http://markmail.org/message/aits7awvwxyk7xch?q=list:net.java.dev.jersey.users+selectVariant+order:date-backward).
