### ISSUE TITLE
Return URL for one-off payments

### ISSUE THREAD

**Issue by chris13524** [killbill/killbill-paypal-express-plugin#30]
I'm attempting to make a [one-off payment without a pending payment](https://github.com/killbill/killbill-paypal-express-plugin#without-a-pending-payment). When the user returns from the authorization, he gets redirected to http://example.com/success?token=thetoken.

Of course, this isn't desired, and I'd like to know how I can specify the return and cancel URLs for the hosted form stuff.

**Comment by pierre** [comment]
Please use the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) for support questions (see [CONTRIBUTING](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md)).
