### ISSUE TITLE
Recurring payments via a billing agreement ID (BAID) : Token expire

### ISSUE THREAD

**Issue by ramezmagdy** [killbill/killbill-paypal-express-plugin#32]
Hi,
i have followed the installation instructions and the Recurring payments via a billing agreement ID (BAID) instruction but on every recurring payment i get this message "This Express Checkout session has expired. Token value is no longer valid."
so there is any thing i'm missing or i have to do ?

**Comment by pierre** [comment]
Please use the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) for implementation questions. See also https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md for reporting issues.
