### ISSUE TITLE
Production mode doesn't work

### ISSUE THREAD

**Issue by suquant** [killbill/killbill-paypal-express-plugin#45]
Hi all,

As mention in the readme file for go to production need to create file paypal_express.yml configuration file under /var/tmp/bundles/plugins/ruby/killbill-paypal-express/x.y.z/ containing the following:

```
:paypal_express:
  :test: false
``` 

I am using KillBill 0.20.11 with paypal-express plugin version of 6.0.0
If I properly understood the instruction above I have to create /var/tmp/bundles/plugins/ruby/killbill-paypal-express/6.0.0/paypal_express.yml  containing mentioned above content.

Am I doing something wrong? Because the instruction doesn't work as expected, the plugin still trying to connect to paypal's sandbox api.

Thank you.

**Comment by pierre** [comment]
Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See [CONTRIBUTING.md](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
